// <auto-generated />
using System;
using GeoPointAPI.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoPointAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260217161951_AddSoftDelete")]
    partial class AddSoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoPointAPI.Models.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<string>("GoogleDriveFileId")
                        .HasColumnType("text")
                        .HasColumnName("google_drive_file_id");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("ATTACHMENTS");
                });

            modelBuilder.Entity("GeoPointAPI.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("EntityAffected")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_affected");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp_utc");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.ToTable("AUDIT_LOGS");
                });

            modelBuilder.Entity("GeoPointAPI.Models.DailyBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BalanceMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("balance_minutes");

                    b.Property<int>("OvertimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("overtime_minutes");

                    b.Property<DateTime>("ReferenceDate")
                        .HasColumnType("date")
                        .HasColumnName("reference_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Status");

                    b.Property<int>("TotalWorkedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("total_worked_minutes");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DAILYBALANCES");
                });

            modelBuilder.Entity("GeoPointAPI.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("RadiusMeters")
                        .HasColumnType("integer")
                        .HasColumnName("radius_meters");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LOCATIONS");
                });

            modelBuilder.Entity("GeoPointAPI.Models.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("JustificationReviewer")
                        .HasColumnType("text")
                        .HasColumnName("justification_reviewer");

                    b.Property<string>("JustificationUser")
                        .HasColumnType("text")
                        .HasColumnName("justification_user");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("target_date");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("REQUESTS");
                });

            modelBuilder.Entity("GeoPointAPI.Models.TimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsManualAdjustment")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manual_adjustment");

                    b.Property<decimal>("LatitudeRecorded")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10, 8)")
                        .HasColumnName("latitude_recorded");

                    b.Property<decimal>("LongitudeRecorded")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11, 8)")
                        .HasColumnName("longitude_recorded");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TIME_ENTRIES");
                });

            modelBuilder.Entity("GeoPointAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jobtitle");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("WorkScheduleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("work_schedule_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkScheduleId");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("GeoPointAPI.Models.WorkSchedule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.Property<int>("ToleranceMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("tolerance_minutes");

                    b.Property<int[]>("WorkDays")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("work_days");

                    b.HasKey("Id");

                    b.ToTable("WORK_SCHEDULES");

                    b.HasData(
                        new
                        {
                            Id = "Comercial",
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            Name = "Comercial (08h-18h)",
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            ToleranceMinutes = 10,
                            WorkDays = new[] { 1, 2, 3, 4, 5 }
                        },
                        new
                        {
                            Id = "Intern",
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            Name = "Intern (08h-15h)",
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            ToleranceMinutes = 15,
                            WorkDays = new[] { 1, 2, 3, 4, 5 }
                        },
                        new
                        {
                            Id = "Contractor",
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            Name = "Contractor (09h-18h)",
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            ToleranceMinutes = 5,
                            WorkDays = new[] { 1, 2, 3, 4, 5 }
                        });
                });

            modelBuilder.Entity("GeoPointAPI.Models.Attachment", b =>
                {
                    b.HasOne("GeoPointAPI.Models.Request", "Request")
                        .WithMany("Attachments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("GeoPointAPI.Models.AuditLog", b =>
                {
                    b.HasOne("GeoPointAPI.Models.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("GeoPointAPI.Models.DailyBalance", b =>
                {
                    b.HasOne("GeoPointAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoPointAPI.Models.Location", b =>
                {
                    b.HasOne("GeoPointAPI.Models.User", "User")
                        .WithMany("Locations")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoPointAPI.Models.Request", b =>
                {
                    b.HasOne("GeoPointAPI.Models.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeoPointAPI.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Requester");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("GeoPointAPI.Models.TimeEntry", b =>
                {
                    b.HasOne("GeoPointAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoPointAPI.Models.User", b =>
                {
                    b.HasOne("GeoPointAPI.Models.WorkSchedule", "WorkSchedule")
                        .WithMany("Users")
                        .HasForeignKey("WorkScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkSchedule");
                });

            modelBuilder.Entity("GeoPointAPI.Models.Request", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("GeoPointAPI.Models.User", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("GeoPointAPI.Models.WorkSchedule", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
