// <auto-generated />
using System;
using GeoPointAPI.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoPointAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoPointAPI.Models.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("ATTACHMENTS");
                });

            modelBuilder.Entity("GeoPointAPI.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("EntityAffected")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_affected");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp_utc");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.ToTable("AUDIT_LOGS");
                });

            modelBuilder.Entity("GeoPointAPI.Models.DailyBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BalanceMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("balance_minutes");

                    b.Property<int>("OvertimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("overtime_minutes");

                    b.Property<DateTime>("ReferenceDate")
                        .HasColumnType("date")
                        .HasColumnName("reference_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Status");

                    b.Property<int>("TotalWorkedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("total_worked_minutes");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DAILYBALANCES");
                });

            modelBuilder.Entity("GeoPointAPI.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("RadiusMeters")
                        .HasColumnType("integer")
                        .HasColumnName("radius_meters");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LOCATIONS");
                });

            modelBuilder.Entity("GeoPointAPI.Models.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("JustificationUser")
                        .HasColumnType("text")
                        .HasColumnName("justification_user");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("target_date");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("REQUESTS");
                });

            modelBuilder.Entity("GeoPointAPI.Models.TimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsManualAdjustment")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manual_adjustment");

                    b.Property<decimal>("LatitudeRecorded")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10, 8)")
                        .HasColumnName("latitude_recorded");

                    b.Property<decimal>("LongitudeRecorded")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11, 8)")
                        .HasColumnName("longitude_recorded");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TIME_ENTRIES");
                });

            modelBuilder.Entity("GeoPointAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_schedule_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkScheduleId");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("GeoPointAPI.Models.WorkSchedules", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeSpan>("DailyHoursTarget")
                        .HasColumnType("interval")
                        .HasColumnName("daily_hours_target");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("ToleranceMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("tolerance_minutes");

                    b.Property<int[]>("WorkDays")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("work_days");

                    b.HasKey("Id");

                    b.ToTable("WORK_SCHEDULES");
                });

            modelBuilder.Entity("GeoPointAPI.Models.Attachment", b =>
                {
                    b.HasOne("GeoPointAPI.Models.Request", "Request")
                        .WithMany("Attachments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("GeoPointAPI.Models.AuditLog", b =>
                {
                    b.HasOne("GeoPointAPI.Models.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("GeoPointAPI.Models.DailyBalance", b =>
                {
                    b.HasOne("GeoPointAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoPointAPI.Models.Location", b =>
                {
                    b.HasOne("GeoPointAPI.Models.User", "User")
                        .WithMany("Locations")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoPointAPI.Models.Request", b =>
                {
                    b.HasOne("GeoPointAPI.Models.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeoPointAPI.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Requester");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("GeoPointAPI.Models.TimeEntry", b =>
                {
                    b.HasOne("GeoPointAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoPointAPI.Models.User", b =>
                {
                    b.HasOne("GeoPointAPI.Models.WorkSchedules", "WorkSchedule")
                        .WithMany("Users")
                        .HasForeignKey("WorkScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkSchedule");
                });

            modelBuilder.Entity("GeoPointAPI.Models.Request", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("GeoPointAPI.Models.User", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("GeoPointAPI.Models.WorkSchedules", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
