name: Deploy to MonsterASP

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publicar Aplicação (Release)
        run: dotnet publish ./GeoPointAPI/GeoPointAPI.sln -c Release -o ./publish_folder

      # 🪄 NOVO: Manda o arquivo mágico para desligar a API e destrancar as .dll
      - name: Colocar API Offline (Liberar Arquivos)
        run: |
          echo "Atualizando o sistema..." > app_offline.htm
          curl -T app_offline.htm ftp://${{ secrets.FTP_SERVER }}/wwwroot/app_offline.htm --user "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}"

      # Faz o upload dos arquivos novos (agora destrancados!)
      - name: Enviar para o Servidor via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish_folder/
          server-dir: /wwwroot/

      # 🪄 NOVO: Apaga o arquivo mágico para a API voltar a funcionar com o código novo
      - name: Religar API
        run: curl -Q "DELE /wwwroot/app_offline.htm" ftp://${{ secrets.FTP_SERVER }}/ --user "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}"
